# Generated by Django 4.0.6 on 2022-08-10 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_new_image_post_alter_post_image_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="new_image_post",
        ),
    ]
